import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { RotateCcw, Play, Pause, Trophy, Volume2, VolumeX, Undo2, ArrowUp, ArrowDown, ArrowLeft, ArrowRight, Share2, Sparkles } from 'lucide-react';

function useBest(key, initial = 0) {
  const [best, setBest] = useState(() => { try { return Number(localStorage.getItem(`arcade:${key}`)) || initial; } catch { return initial; } });
  const update = useCallback((value) => { setBest((old) => { const next = Math.max(old, value); try { localStorage.setItem(`arcade:${key}`, String(next)); } catch {} return next; }); }, [key]);
  return [best, update];
}
function useMinBest(key) {
  const [best, setBest] = useState(() => { try { return Number(localStorage.getItem(`arcade:${key}`)) || 0; } catch { return 0; } });
  const update = useCallback((value) => { if (!value) return; setBest((old) => { const next = old ? Math.min(old, value) : value; try { localStorage.setItem(`arcade:${key}`, String(next)); } catch {} return next; }); }, [key]);
  return [best, update];
}

function Stat({ label, value, accent }) { return <div className={`arcade-stat ${accent ? 'is-accent' : ''}`}><span>{label}</span><strong>{value}</strong></div>; }
function GameAction({ children, onClick, variant = 'secondary', disabled = false }) { return <button className={`arcade-button arcade-button--${variant}`} type="button" onClick={onClick} disabled={disabled}>{children}</button>; }

function MemoryGame() {
  const levels = { Quick: 6, Classic: 8, Expert: 10 };
  const [level, setLevel] = useState('Classic');
  const [cards, setCards] = useState(() => shuffleIcons(levels.Classic));
  const [open, setOpen] = useState([]); const [matched, setMatched] = useState([]); const [moves, setMoves] = useState(0); const [seconds, setSeconds] = useState(0); const [started, setStarted] = useState(false);
  const [best, setBest] = useMinBest('memory-best');
  const done = matched.length === cards.length;
  useEffect(() => { if (!started || done) return undefined; const id = setInterval(() => setSeconds((s) => s + 1), 1000); return () => clearInterval(id); }, [started, done]);
  useEffect(() => { if (open.length !== 2) return undefined; const id = setTimeout(() => { if (cards[open[0]] === cards[open[1]]) setMatched((v) => [...v, ...open]); setOpen([]); }, 700); return () => clearTimeout(id); }, [open, cards]);
  useEffect(() => { if (done && moves) setBest(moves); }, [done, moves, setBest]);
  function restart(nextLevel = level) { setLevel(nextLevel); setCards(shuffleIcons(levels[nextLevel])); setOpen([]); setMatched([]); setMoves(0); setSeconds(0); setStarted(false); }
  return <div className="arcade-game-content">
    <div className="arcade-game-top"><div className="arcade-stats"><Stat label="Moves" value={moves} /><Stat label="Pairs" value={`${matched.length / 2}/${cards.length / 2}`} /><Stat label="Time" value={formatTime(seconds)} /></div><GameAction onClick={() => restart()}><RotateCcw size={16} /> New game</GameAction></div>
    <div className={`memory-grid memory-grid--${cards.length / 2}`}>{cards.map((card, i) => <button key={`${card}-${i}`} className={`memory-tile ${open.includes(i) || matched.includes(i) ? 'is-open' : ''} ${matched.includes(i) ? 'is-matched' : ''}`} onClick={() => { if (open.length < 2 && !open.includes(i) && !matched.includes(i)) { setStarted(true); setOpen((v) => [...v, i]); if (open.length === 1) setMoves((v) => v + 1); } }} disabled={open.length === 2 || matched.includes(i)} aria-label={matched.includes(i) || open.includes(i) ? card.label : 'Flip hidden card'}><span>{matched.includes(i) || open.includes(i) ? card.icon : <Sparkles size={20} />}</span></button>)}</div>
    <div className="arcade-game-bottom"><div className="game-levels" aria-label="Choose difficulty">{Object.keys(levels).map((name) => <button key={name} className={level === name ? 'is-selected' : ''} onClick={() => restart(name)}>{name}</button>)}</div><span className="arcade-hint">Best: {best ? `${best} moves` : '—'}</span></div>
    {done && <ResultBanner title="Board cleared!" detail={`You found every pair in ${moves} moves and ${formatTime(seconds)}.`} action={() => restart()} />}
  </div>;
}
function shuffleIcons(pairs) { const faces = [{ icon: '🍋', label: 'Lemon' }, { icon: '🍇', label: 'Grapes' }, { icon: '🍒', label: 'Cherries' }, { icon: '🥝', label: 'Kiwi' }, { icon: '🍉', label: 'Watermelon' }, { icon: '🍊', label: 'Orange' }, { icon: '🍍', label: 'Pineapple' }, { icon: '🥥', label: 'Coconut' }, { icon: '🍓', label: 'Strawberry' }, { icon: '🫐', label: 'Blueberries' }]; return [...faces.slice(0, pairs), ...faces.slice(0, pairs)].sort(() => Math.random() - .5); }

function ReflexGame() {
  const [phase, setPhase] = useState('intro'); const [round, setRound] = useState(0); const [times, setTimes] = useState([]); const [shownAt, setShownAt] = useState(0); const [last, setLast] = useState(null); const timeout = useRef(); const [best, setBest] = useMinBest('reflex-best');
  const ROUND_COUNT = 5;
  const beginRound = useCallback(() => { clearTimeout(timeout.current); setPhase('waiting'); timeout.current = setTimeout(() => { setShownAt(performance.now()); setPhase('go'); }, 1300 + Math.random() * 2700); }, []);
  useEffect(() => () => clearTimeout(timeout.current), []);
  const start = () => { setRound(0); setTimes([]); setLast(null); beginRound(); };
  const tap = () => {
    if (phase === 'intro' || phase === 'done' || phase === 'false-start') { start(); return; }
    if (phase === 'waiting') { clearTimeout(timeout.current); setPhase('false-start'); return; }
    if (phase !== 'go') return;
    const ms = Math.round(performance.now() - shownAt); const next = [...times, ms]; setTimes(next); setLast(ms); setRound(next.length);
    if (next.length === ROUND_COUNT) { setPhase('done'); setBest(Math.round(next.reduce((a, b) => a + b, 0) / next.length)); } else beginRound();
  };
  const average = times.length ? Math.round(times.reduce((a, b) => a + b, 0) / times.length) : 0;
  return <div className="arcade-game-content">
    <div className="arcade-game-top"><div className="arcade-stats"><Stat label="Round" value={`${Math.min(round + (phase === 'waiting' || phase === 'go' ? 1 : 0), ROUND_COUNT)}/${ROUND_COUNT}`} /><Stat label="Last" value={last ? `${last} ms` : '—'} /><Stat label="Personal best" value={best ? `${best} ms` : '—'} accent /></div><GameAction onClick={start}><RotateCcw size={16} /> Restart</GameAction></div>
    <button className={`reflex-stage reflex-stage--${phase}`} onClick={tap} aria-live="polite"><span className="reflex-orb"><span /></span><span className="reflex-instruction">{phase === 'intro' ? 'Ready when you are' : phase === 'waiting' ? 'Wait for the glow…' : phase === 'go' ? 'TAP NOW!' : phase === 'false-start' ? 'Too soon. Tap to retry.' : phase === 'done' ? `${average} ms average` : 'Tap to start'}</span><span className="reflex-subline">{phase === 'intro' || phase === 'false-start' || phase === 'done' ? 'Tap anywhere in this panel' : phase === 'waiting' ? 'Stay focused' : 'Tap as quickly as you can'}</span></button>
    <div className="reflex-history" aria-label="Reaction time results">{Array.from({ length: ROUND_COUNT }, (_, i) => <div className={`reflex-result ${times[i] ? 'has-result' : ''}`} key={i}><span>0{i + 1}</span><strong>{times[i] ? `${times[i]} ms` : '—'}</strong></div>)}</div>
    {phase === 'done' && <ResultBanner title={average < 250 ? 'Lightning fast!' : 'Nice reactions!'} detail={`Your average across five rounds was ${average} ms.`} action={start} label="Try again" />}
  </div>;
}

const COLORS = ['#fa547c', '#f7b83d', '#34c99a', '#5488ff'];
function ColorGame() {
  const [sequence, setSequence] = useState([]); const [input, setInput] = useState([]); const [lit, setLit] = useState(-1); const [phase, setPhase] = useState('idle'); const [level, setLevel] = useState(0); const [sound, setSound] = useState(false); const [best, setBest] = useBest('color-best', 0); const timers = useRef([]); const token = useRef(0);
  const clearTimers = () => { timers.current.forEach(clearTimeout); timers.current = []; };
  useEffect(() => () => { token.current += 1; clearTimers(); }, []);
  const play = useCallback((values) => { clearTimers(); token.current += 1; const current = token.current; setPhase('watch'); setInput([]); values.forEach((value, index) => { timers.current.push(setTimeout(() => { if (token.current === current) { setLit(value); if (sound) { try { const audio = new AudioContext(); const osc = audio.createOscillator(); const gain = audio.createGain(); osc.frequency.value = [310, 390, 480, 590][value]; gain.gain.value = .035; osc.connect(gain).connect(audio.destination); osc.start(); osc.stop(audio.currentTime + .12); osc.onended = () => audio.close(); } catch {} } } }, 500 + index * 760)); timers.current.push(setTimeout(() => { if (token.current === current) setLit(-1); }, 810 + index * 760)); }); timers.current.push(setTimeout(() => { if (token.current === current) setPhase('input'); }, 500 + values.length * 760)); }, [sound]);
  const start = () => { const next = [Math.floor(Math.random() * 4)]; setSequence(next); setLevel(1); setPhase('watch'); play(next); };
  const choose = (i) => { if (phase !== 'input') return; const next = [...input, i]; setInput(next); if (sequence[next.length - 1] !== i) { setPhase('over'); setBest(level - 1); return; } if (next.length === sequence.length) { const longer = [...sequence, Math.floor(Math.random() * 4)]; setSequence(longer); setLevel(longer.length); setPhase('watch'); timers.current.push(setTimeout(() => play(longer), 450)); } };
  return <div className="arcade-game-content"><div className="arcade-game-top"><div className="arcade-stats"><Stat label="Level" value={level || '—'} /><Stat label="Best run" value={best} accent /><Stat label="Status" value={phase === 'watch' ? 'Watch' : phase === 'input' ? 'Repeat' : phase === 'over' ? 'Finished' : 'Ready'} /></div><button className="arcade-icon-button" onClick={() => setSound((v) => !v)} aria-label={sound ? 'Mute sound' : 'Enable sound'}>{sound ? <Volume2 size={18} /> : <VolumeX size={18} />}</button></div>
    <div className="color-game-wrap"><div className="color-game-board">{COLORS.map((color, i) => <button type="button" key={color} className={`color-game-pad color-game-pad--${i} ${lit === i ? 'is-lit' : ''}`} style={{ '--pad-color': color }} onClick={() => choose(i)} disabled={phase !== 'input'} aria-label={`Color ${i + 1}`} />)}</div><div className="color-game-center"><strong>{level ? String(level).padStart(2, '0') : 'GO'}</strong><span>{phase === 'watch' ? 'Watch' : phase === 'input' ? 'Your turn' : phase === 'over' ? 'Game over' : 'Memory'}</span></div></div>
    <div className="arcade-game-bottom"><p className="arcade-hint">Repeat the growing color sequence in the same order.</p><GameAction variant="primary" onClick={start}><Play size={16} /> {phase === 'over' ? 'Play again' : level ? 'Restart sequence' : 'Start game'}</GameAction></div>{phase === 'over' && <ResultBanner title={`You reached level ${level - 1}`} detail="Every round adds one more color to the sequence." action={start} label="Try again" />}</div>;
}

const WORDS = ['crane','plant','brick','shine','ghost','frame','cloud','grape','piano','lemon','smile','beach','trail','spark','flame','charm','novel','sugar','tiger','dream','proud','storm','quiet','fresh','badge','crown','light','space','world','green','radio','ocean','magic','heart','dance','vivid','water','fruit','march','queen','knock','width','apple','point','prize','learn','sweep','train','about','under','other','there','house','story','sound','break','brown','sweet','table','night','party','music','adore','worry','black','white','guess','focus','ready','share','smoke','craft','clock','stone','laugh','grace','spice','slope','sheep','tears','drive','mouse','skill','arrow','range','rider','court','river','pearl','cabin','habit','brush','scene','trust','major','faith','total','group','serve','union','write'];
function dateStamp() { const d = new Date(); return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`; }
function wordOfTheDay() { const d = new Date(); const day = Math.floor(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()) / 86400000); return WORDS[day % WORDS.length]; }
function WordleGame() {
  const answer = useMemo(wordOfTheDay, []); const puzzleKey = `arcade:wordle:${dateStamp()}`; const [guess, setGuess] = useState(''); const [rows, setRows] = useState(() => { try { const saved = JSON.parse(localStorage.getItem(puzzleKey) || '[]'); return Array.isArray(saved) ? saved.filter((word) => typeof word === 'string' && word.length === 5).slice(0, 6) : []; } catch { return []; } }); const [message, setMessage] = useState('Type a word, then press Enter.'); const [copied, setCopied] = useState(false); const won = rows.at(-1) === answer; const lost = rows.length === 6 && !won; const ended = won || lost;
  useEffect(() => { try { localStorage.setItem(puzzleKey, JSON.stringify(rows)); } catch {} }, [puzzleKey, rows]);
  const evaluate = (word) => { const result = Array(5).fill('absent'); const remaining = answer.split(''); for (let i = 0; i < 5; i += 1) if (word[i] === answer[i]) { result[i] = 'correct'; remaining[i] = ''; } for (let i = 0; i < 5; i += 1) if (result[i] !== 'correct') { const index = remaining.indexOf(word[i]); if (index !== -1) { result[i] = 'present'; remaining[index] = ''; } } return result; };
  const submit = (word = guess) => { const next = word.trim().toLowerCase(); if (next.length !== 5) { setMessage('Your guess needs five letters.'); return; } if (!WORDS.includes(next)) { setMessage('Choose a word from the game dictionary.'); return; } if (ended) return; setRows((v) => [...v, next]); setGuess(''); setMessage(next === answer ? 'Brilliant — you found it!' : rows.length === 5 ? `The word was ${answer.toUpperCase()}.` : ''); };
  useEffect(() => { const onKey = (e) => { if (e.key === 'Enter') { e.preventDefault(); submit(); } else if (e.key === 'Backspace') setGuess((v) => v.slice(0, -1)); else if (/^[a-z]$/i.test(e.key) && guess.length < 5 && !ended) setGuess((v) => (v + e.key).slice(0, 5)); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); });
  const share = async () => { const blocks = rows.map((row) => evaluate(row).map((state) => state === 'correct' ? '🟩' : state === 'present' ? '🟨' : '⬛').join('')).join('\n'); const text = `HavitGrowth Wordle ${won ? rows.length : 'X'}/6\n\n${blocks}`; try { await navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1600); } catch { setMessage('Clipboard unavailable in this browser.'); } };
  const keyboardStatus = (letter) => rows.flatMap((row) => row.split('').map((char, i) => [char, evaluate(row)[i]])).filter(([char]) => char === letter.toLowerCase()).map(([, state]) => state).sort((a, b) => ['absent','present','correct'].indexOf(b) - ['absent','present','correct'].indexOf(a))[0] || '';
  return <div className="arcade-game-content wordle-content"><div className="arcade-game-top"><div className="arcade-stats"><Stat label="Attempts" value={`${rows.length}/6`} /><Stat label="Mode" value="Daily" /><Stat label="Puzzle" value={new Date().toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} /></div><GameAction onClick={share} disabled={!rows.length}><Share2 size={15} /> {copied ? 'Copied!' : 'Share'}</GameAction></div>
    <div className="wordle-board" role="grid" aria-label="Word puzzle board">{Array.from({ length: 6 }, (_, r) => <div className="wordle-row" role="row" key={r}>{Array.from({ length: 5 }, (_, c) => { const value = rows[r]?.[c] || (r === rows.length ? guess[c] : ''); const result = rows[r] ? evaluate(rows[r])[c] : ''; return <span role="gridcell" className={`wordle-cell ${result} ${value && !result ? 'has-letter' : ''}`} key={c}>{value?.toUpperCase() || ''}</span>; })}</div>)}</div>
    <p className={`wordle-message ${ended ? 'is-result' : ''}`} aria-live="polite">{won ? 'Excellent! Come back tomorrow for a new word.' : lost ? `The answer was ${answer.toUpperCase()}. Come back tomorrow for another.` : message}</p>
    <div className="wordle-keyboard">{['QWERTYUIOP','ASDFGHJKL','ENTERZXCVBNMDEL'].map((row, r) => <div className="wordle-key-row" key={r}>{(r === 2 ? ['ENTER', ...'ZXCVBNM'.split(''), 'DEL'] : row.split('')).map((key) => <button key={key} className={`wordle-key ${key.length > 1 ? 'wordle-key--wide' : ''} ${keyboardStatus(key)}`} onClick={() => key === 'ENTER' ? submit() : key === 'DEL' ? setGuess((v) => v.slice(0, -1)) : setGuess((v) => !ended && v.length < 5 ? (v + key.toLowerCase()).slice(0, 5) : v)} disabled={ended}>{key}</button>)}</div>)}</div>
    {ended && <div className="wordle-end"><strong>{won ? 'Puzzle solved' : 'Come back tomorrow'}</strong><span>A new daily word is ready at midnight.</span><GameAction onClick={share}><Share2 size={15} /> {copied ? 'Copied!' : 'Share result'}</GameAction></div>}</div>;
}

function makeBoard() { const b = Array(16).fill(0); addTile(b); return b; }
function addTile(b) { const empty = b.map((n, i) => n ? -1 : i).filter((i) => i >= 0); if (empty.length) b[empty[Math.floor(Math.random() * empty.length)]] = Math.random() < .9 ? 2 : 4; }
function shift2048(board, direction) { const next = Array(16).fill(0); let gained = 0; for (let line = 0; line < 4; line += 1) { const indices = Array.from({ length: 4 }, (_, slot) => direction === 'left' || direction === 'right' ? line * 4 + slot : slot * 4 + line); let values = indices.map((i) => board[i]).filter(Boolean); if (direction === 'right' || direction === 'down') values.reverse(); for (let i = 0; i < values.length - 1; i += 1) if (values[i] === values[i + 1]) { values[i] *= 2; gained += values[i]; values.splice(i + 1, 1); } while (values.length < 4) values.push(0); if (direction === 'right' || direction === 'down') values.reverse(); indices.forEach((index, i) => { next[index] = values[i]; }); } return { next, gained, changed: next.some((v, i) => v !== board[i]) }; }
function canMove2048(board) { if (board.includes(0)) return true; for (let i = 0; i < 16; i += 1) if ((i % 4 < 3 && board[i] === board[i + 1]) || (i < 12 && board[i] === board[i + 4])) return true; return false; }
function PuzzleGame() {
  const [board, setBoard] = useState(makeBoard); const [score, setScore] = useState(0); const [best, setBest] = useBest('2048-best', 0); const [won, setWon] = useState(false); const [keepPlaying, setKeepPlaying] = useState(false); const [previous, setPrevious] = useState(null); const [touch, setTouch] = useState(null); const ended = !canMove2048(board);
  const move = useCallback((direction) => { if (ended || (won && !keepPlaying)) return; const result = shift2048(board, direction); if (!result.changed) return; setPrevious({ board, score }); const next = result.next; addTile(next); setBoard(next); const newScore = score + result.gained; setScore(newScore); setBest(newScore); if (!won && next.some((v) => v >= 2048)) setWon(true); }, [board, ended, keepPlaying, score, setBest, won]);
  useEffect(() => { const key = (e) => { const dirs = { ArrowLeft: 'left', ArrowRight: 'right', ArrowUp: 'up', ArrowDown: 'down', a: 'left', d: 'right', w: 'up', s: 'down' }; const direction = dirs[e.key] || dirs[e.key.toLowerCase()]; if (direction) { e.preventDefault(); move(direction); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [move]);
  const restart = () => { setBoard(makeBoard()); setScore(0); setPrevious(null); setWon(false); setKeepPlaying(false); };
  const directions = [{ id: 'up', icon: ArrowUp }, { id: 'left', icon: ArrowLeft }, { id: 'down', icon: ArrowDown }, { id: 'right', icon: ArrowRight }];
  return <div className="arcade-game-content"><div className="arcade-game-top"><div className="arcade-stats"><Stat label="Score" value={score} accent /><Stat label="Best" value={best} /><Stat label="Target" value="2048" /></div><div className="arcade-actions"><GameAction onClick={() => { if (!previous) return; setBoard(previous.board); setScore(previous.score); setPrevious(null); setWon(false); }} disabled={!previous}><Undo2 size={16} /> Undo</GameAction><GameAction onClick={restart}><RotateCcw size={16} /> New game</GameAction></div></div>
    <div className="puzzle-board" onTouchStart={(e) => setTouch([e.touches[0].clientX, e.touches[0].clientY])} onTouchEnd={(e) => { if (!touch) return; const dx = e.changedTouches[0].clientX - touch[0]; const dy = e.changedTouches[0].clientY - touch[1]; if (Math.max(Math.abs(dx), Math.abs(dy)) > 22) move(Math.abs(dx) > Math.abs(dy) ? dx > 0 ? 'right' : 'left' : dy > 0 ? 'down' : 'up'); setTouch(null); }} aria-label="2048 game board">{board.map((n, i) => <div className={`puzzle-cell ${n ? `tile-${Math.min(n, 2048)}` : ''}`} key={i}>{n || ''}</div>)}</div>
    <div className="puzzle-mobile-controls">{directions.map(({ id, icon: Icon }) => <button key={id} onClick={() => move(id)} aria-label={`Move ${id}`}><Icon size={19} /></button>)}</div><p className="arcade-hint arcade-center">Use arrow keys or WASD. On touch screens, swipe the board or use the arrows.</p>
    {won && !keepPlaying && <ResultBanner title="2048! You did it." detail="Keep playing to beat your high score, or start a fresh board." action={() => setKeepPlaying(true)} label="Keep playing" secondary={() => restart()} secondaryLabel="New game" />}{ended && <ResultBanner title="No moves left" detail={`Final score: ${score}. Your best is ${best}.`} action={restart} label="Play again" />}</div>;
}

const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
function winningLine(cells) { return LINES.find(([a,b,c]) => cells[a] && cells[a] === cells[b] && cells[a] === cells[c]); }
function minimax(cells, player, depth = 0) { const line = winningLine(cells); if (line) return { score: cells[line[0]] === 'O' ? 10 - depth : depth - 10 }; const open = cells.map((v,i) => v ? null : i).filter((v) => v !== null); if (!open.length) return { score: 0 }; let best = { score: player === 'O' ? -Infinity : Infinity }; for (const index of open) { const next = [...cells]; next[index] = player; const candidate = { index, score: minimax(next, player === 'O' ? 'X' : 'O', depth + 1).score }; if (player === 'O' ? candidate.score > best.score : candidate.score < best.score) best = candidate; } return best; }
function TicTacToe() {
  const [board, setBoard] = useState(Array(9).fill('')); const [turn, setTurn] = useState('X'); const [mode, setMode] = useState('ai'); const [difficulty, setDifficulty] = useState('Expert'); const [scores, setScores] = useState({ X: 0, O: 0, draw: 0 });
  const line = winningLine(board); const result = line ? board[line[0]] : board.every(Boolean) ? 'draw' : ''; const aiThinking = mode === 'ai' && turn === 'O' && !result; const scored = useRef('');
  const place = useCallback((index, mark = turn) => { setBoard((current) => { if (current[index] || winningLine(current) || current.every(Boolean)) return current; const next = [...current]; next[index] = mark; return next; }); setTurn(mark === 'X' ? 'O' : 'X'); }, [turn]);
  useEffect(() => { if (!result) return; const key = board.join(''); if (scored.current === key) return; scored.current = key; if (result === 'draw') setScores((s) => ({ ...s, draw: s.draw + 1 })); else setScores((s) => ({ ...s, [result]: s[result] + 1 })); }, [board, result]);
  useEffect(() => { if (mode !== 'ai' || turn !== 'O' || result) return undefined; const id = setTimeout(() => { const best = minimax(board, 'O'); const index = difficulty === 'Easy' && Math.random() < .48 ? board.map((v,i) => v ? null : i).filter((v) => v !== null)[Math.floor(Math.random() * board.filter((v) => !v).length)] : best.index; if (index !== undefined) place(index, 'O'); }, 450); return () => clearTimeout(id); }, [board, difficulty, mode, place, result, turn]);
  const reset = (resetScores = false) => { scored.current = ''; setBoard(Array(9).fill('')); setTurn('X'); if (resetScores) setScores({ X: 0, O: 0, draw: 0 }); };
  return <div className="arcade-game-content"><div className="arcade-game-top"><div className="arcade-stats"><Stat label="You · X" value={scores.X} accent /><Stat label={mode === 'ai' ? 'AI · O' : 'Player O'} value={scores.O} /><Stat label="Draws" value={scores.draw} /></div><GameAction onClick={() => { setMode((v) => v === 'ai' ? 'local' : 'ai'); reset(); }}>{mode === 'ai' ? '2 players' : 'Play AI'}</GameAction></div>
    <div className="tictactoe-options">{mode === 'ai' ? <label>AI level<select value={difficulty} onChange={(e) => setDifficulty(e.target.value)}><option>Easy</option><option>Expert</option></select></label> : <span>Local two-player mode</span>}<GameAction onClick={() => reset()}><RotateCcw size={15} /> New round</GameAction></div>
    <div className="tic-board" role="grid" aria-label="Tic-tac-toe board">{board.map((cell, i) => <button key={i} role="gridcell" className={`${cell ? `mark-${cell.toLowerCase()}` : ''} ${line?.includes(i) ? 'is-winning' : ''}`} onClick={() => { if (!aiThinking && !result) place(i); }} disabled={Boolean(cell) || Boolean(result) || aiThinking} aria-label={`Square ${i + 1}${cell ? `: ${cell}` : ''}`}>{cell}</button>)}</div>
    <p className="arcade-hint arcade-center">{result ? result === 'draw' ? 'A well-played draw.' : result === 'X' ? 'You win this round!' : mode === 'ai' ? 'The AI takes this round.' : 'Player O wins this round.' : aiThinking ? 'The AI is thinking…' : `${mode === 'ai' ? 'Your' : `Player ${turn}'s`} turn${mode === 'ai' ? '' : ` (${turn})`}`}</p>
    {result && <ResultBanner title={result === 'draw' ? 'It’s a draw.' : result === 'X' ? 'Round to you!' : 'Round to O'} detail="The match score is saved above. Ready for another round?" action={() => reset()} label="Next round" secondary={() => reset(true)} secondaryLabel="Reset match" />}</div>;
}

function SnakeGame() {
  const SIDE = 18; const [snake, setSnake] = useState([Math.floor(SIDE * SIDE / 2), Math.floor(SIDE * SIDE / 2) - 1, Math.floor(SIDE * SIDE / 2) - 2]); const [food, setFood] = useState(55); const [direction, setDirection] = useState('right'); const dirRef = useRef('right'); const [status, setStatus] = useState('ready'); const [score, setScore] = useState(0); const [speed, setSpeed] = useState('Normal'); const [best, setBest] = useBest('snake-best', 0); const touchStart = useRef(null); const speedMs = { Calm: 180, Normal: 135, Fast: 95 };
  const reset = () => { setSnake([Math.floor(SIDE * SIDE / 2), Math.floor(SIDE * SIDE / 2) - 1, Math.floor(SIDE * SIDE / 2) - 2]); setFood(Math.floor(Math.random() * SIDE * SIDE)); setDirection('right'); dirRef.current = 'right'; setScore(0); setStatus('playing'); };
  const turn = useCallback((next) => { if (next === 'up' && dirRef.current === 'down' || next === 'down' && dirRef.current === 'up' || next === 'left' && dirRef.current === 'right' || next === 'right' && dirRef.current === 'left') return; dirRef.current = next; setDirection(next); setStatus((v) => v === 'ready' ? 'playing' : v); }, []);
  useEffect(() => { const onKey = (e) => { const map = { ArrowUp: 'up', w: 'up', ArrowDown: 'down', s: 'down', ArrowLeft: 'left', a: 'left', ArrowRight: 'right', d: 'right' }; if (map[e.key]) { e.preventDefault(); turn(map[e.key]); } if (e.key === ' ' && status !== 'over') { e.preventDefault(); setStatus((v) => v === 'playing' ? 'paused' : 'playing'); } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [status, turn]);
  useEffect(() => { if (status !== 'playing') return undefined; const id = setInterval(() => { setSnake((current) => { const head = current[0]; const delta = dirRef.current === 'up' ? -SIDE : dirRef.current === 'down' ? SIDE : dirRef.current === 'left' ? -1 : 1; const next = head + delta; const wall = next < 0 || next >= SIDE * SIDE || (delta === 1 && head % SIDE === SIDE - 1) || (delta === -1 && head % SIDE === 0); const eating = next === food; const body = eating ? current : current.slice(0, -1); if (wall || body.includes(next)) { setStatus('over'); setBest(current.length - 3); return current; } if (eating) { setScore((v) => { const fresh = v + 1; setBest(fresh); return fresh; }); let fresh; do { fresh = Math.floor(Math.random() * SIDE * SIDE); } while ([...current, next].includes(fresh)); setFood(fresh); return [next, ...current]; } return [next, ...current.slice(0, -1)]; }); }, speedMs[speed]); return () => clearInterval(id); }, [food, setBest, speed, status]);
  const arrow = [{ id: 'up', Icon: ArrowUp }, { id: 'left', Icon: ArrowLeft }, { id: 'down', Icon: ArrowDown }, { id: 'right', Icon: ArrowRight }];
  return <div className="arcade-game-content"><div className="arcade-game-top"><div className="arcade-stats"><Stat label="Apples" value={score} accent /><Stat label="Best" value={best} /><Stat label="Speed" value={speed} /></div><div className="arcade-actions"><GameAction onClick={() => setStatus((v) => v === 'playing' ? 'paused' : 'playing')} disabled={status === 'ready' || status === 'over'}>{status === 'playing' ? <Pause size={16} /> : <Play size={16} />}{status === 'playing' ? 'Pause' : 'Resume'}</GameAction><GameAction onClick={reset}><RotateCcw size={16} /> Restart</GameAction></div></div>
    <div className="snake-options"><label>Game speed<select value={speed} onChange={(e) => setSpeed(e.target.value)}><option>Calm</option><option>Normal</option><option>Fast</option></select></label><span>Move with arrows/WASD · Space to pause</span></div>
    <div className="snake-board" onTouchStart={(e) => { touchStart.current = [e.touches[0].clientX, e.touches[0].clientY]; }} onTouchEnd={(e) => { if (!touchStart.current) return; const dx = e.changedTouches[0].clientX - touchStart.current[0]; const dy = e.changedTouches[0].clientY - touchStart.current[1]; if (Math.max(Math.abs(dx), Math.abs(dy)) > 15) turn(Math.abs(dx) > Math.abs(dy) ? dx > 0 ? 'right' : 'left' : dy > 0 ? 'down' : 'up'); touchStart.current = null; }} role="img" aria-label={`Snake board, score ${score}`} style={{ '--snake-side': SIDE }}>{Array.from({ length: SIDE * SIDE }, (_, i) => <span key={i} className={`${snake[0] === i ? 'snake-head' : snake.includes(i) ? 'snake-part' : ''} ${food === i ? 'snake-food' : ''}`}>{food === i && '✦'}</span>)}{status !== 'playing' && <div className="snake-overlay"><strong>{status === 'ready' ? 'Ready to slither?' : status === 'paused' ? 'Paused' : 'Game over'}</strong><span>{status === 'over' ? `${score} apples collected` : 'Use the arrows or WASD to move'}</span><GameAction variant="primary" onClick={() => status === 'paused' ? setStatus('playing') : reset()}>{status === 'ready' ? 'Start game' : status === 'paused' ? 'Resume' : 'Play again'}</GameAction></div>}</div>
    <div className="snake-dpad" aria-label="Snake direction controls">{arrow.map(({ id, Icon }) => <button key={id} onClick={() => turn(id)} aria-label={`Move ${id}`}><Icon size={18} /></button>)}</div>
  </div>;
}

const TYPING_TEXTS = [
  'Small steps every day lead to remarkable journeys. Focus on steady progress and let your confidence grow with every word.',
  'The best ideas often arrive when curiosity meets patience. Take a breath, find your rhythm, and keep moving forward.',
  'Practice is not about being perfect. It is about showing up, learning from each attempt, and getting a little faster over time.',
];
function TypingGame() {
  const [passage, setPassage] = useState(0); const [value, setValue] = useState(''); const [seconds, setSeconds] = useState(30); const [status, setStatus] = useState('ready'); const [duration, setDuration] = useState(30); const [elapsedDone, setElapsedDone] = useState(0); const [best, setBest] = useBest('typing-best', 0); const area = useRef(null); const start = useRef(0); const text = TYPING_TEXTS[passage]; const correct = value.split('').filter((c, i) => c === text[i]).length; const accuracy = value.length ? Math.round(correct / value.length * 100) : 100; const elapsed = status === 'ready' ? 0 : status === 'done' ? Math.max(1, elapsedDone) : Math.max(1, duration - seconds); const wpm = elapsed ? Math.round(correct / 5 / (elapsed / 60)) : 0;
  useEffect(() => { if (status !== 'running') return undefined; const id = setInterval(() => { setElapsedDone((v) => v + 1); setSeconds((n) => { if (n <= 1) { clearInterval(id); setStatus('done'); return 0; } return n - 1; }); }, 1000); return () => clearInterval(id); }, [status]);
  useEffect(() => { if (status === 'done') setBest(wpm); }, [best, setBest, status, wpm]);
  useEffect(() => { if (value.length === text.length && status === 'running') setStatus('done'); }, [status, text.length, value.length]);
  const begin = () => { setValue(''); setSeconds(duration); setElapsedDone(0); setStatus('running'); start.current = performance.now(); setTimeout(() => area.current?.focus(), 0); };
  return <div className="arcade-game-content typing-content"><div className="arcade-game-top"><div className="arcade-stats"><Stat label="WPM" value={wpm} accent /><Stat label="Accuracy" value={`${accuracy}%`} /><Stat label="Best WPM" value={best} /></div><GameAction onClick={begin}><RotateCcw size={16} /> Restart</GameAction></div>
    <div className="typing-options"><div className="game-levels">{[15,30,60].map((n) => <button key={n} className={duration === n ? 'is-selected' : ''} onClick={() => { setDuration(n); setSeconds(n); setStatus('ready'); setValue(''); }}>{n}s</button>)}</div><button className="typing-new-prompt" onClick={() => { setPassage((v) => (v + 1) % TYPING_TEXTS.length); setValue(''); setSeconds(duration); setStatus('ready'); }}>New passage <ArrowRight size={14} /></button></div>
    <div className="typing-prompt" onClick={() => status === 'ready' ? begin() : area.current?.focus()}>{text.split('').map((char, i) => <span key={i} className={`${i < value.length ? value[i] === char ? 'typed-correct' : 'typed-wrong' : ''} ${i === value.length && status === 'running' ? 'typing-current' : ''}`}>{char}</span>)}</div>
    {status === 'ready' ? <button className="typing-ready" onClick={begin}><Play size={16} /> Start typing test</button> : <textarea ref={area} aria-label="Type the sample passage" className="typing-input" value={value} onChange={(e) => { if (status !== 'running') return; setValue(e.target.value.slice(0, text.length)); }} placeholder="Start typing the passage above…" disabled={status !== 'running'} rows={3} autoCapitalize="off" autoCorrect="off" spellCheck={false} />}
    <div className="typing-bottom"><div className={`typing-countdown ${seconds <= 5 && status === 'running' ? 'is-low' : ''}`}><span>TIME LEFT</span><strong>{status === 'ready' ? duration : seconds}s</strong></div><span className="arcade-hint">{status === 'ready' ? 'Set your duration, then begin when ready.' : status === 'done' ? `${wpm} WPM · ${accuracy}% accuracy` : 'Keep typing — your WPM updates live.'}</span></div>
    {status === 'done' && <ResultBanner title={`${wpm} words per minute`} detail={`Accuracy ${accuracy}% over ${elapsed} seconds. ${wpm >= best ? 'That is a new personal best!' : 'Give it another go to beat your best.'}`} action={begin} label="Try again" />}</div>;
}

function ResultBanner({ title, detail, action, label = 'Play again', secondary, secondaryLabel }) { return <div className="arcade-result"><span className="arcade-result-icon"><Trophy size={22} /></span><div><strong>{title}</strong><p>{detail}</p></div><div className="arcade-result-actions">{secondary && <GameAction onClick={secondary}>{secondaryLabel}</GameAction>}<GameAction variant="primary" onClick={action}>{label}</GameAction></div></div>; }
function formatTime(s) { return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`; }

export { ColorGame, GameAction, MemoryGame, PuzzleGame, ReflexGame, ResultBanner, SnakeGame, Stat, TicTacToe, TypingGame, WordleGame };
