import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, RotateCcw, Shuffle, Sparkles, Trophy } from 'lucide-react';
import { GameAction, Stat } from './ArcadeGames.jsx';

const FACE_INFO = {
  R: { axis: 0, sign: 1, color: '#ef4444', label: 'Right' }, L: { axis: 0, sign: -1, color: '#f28c28', label: 'Left' },
  U: { axis: 1, sign: -1, color: '#f8fafc', label: 'Up' }, D: { axis: 1, sign: 1, color: '#f5d547', label: 'Down' },
  F: { axis: 2, sign: 1, color: '#22c55e', label: 'Front' }, B: { axis: 2, sign: -1, color: '#3b82f6', label: 'Back' },
};
const DIRS = ['px', 'nx', 'py', 'ny', 'pz', 'nz'];
const DIR_VECTOR = { px:[1,0,0], nx:[-1,0,0], py:[0,1,0], ny:[0,-1,0], pz:[0,0,1], nz:[0,0,-1] };
const SOLVED = makeCube();
function makeCube() { const pieces = []; for (let x = -1; x <= 1; x += 1) for (let y = -1; y <= 1; y += 1) for (let z = -1; z <= 1; z += 1) { const stickers = {}; if (x === 1) stickers.px = FACE_INFO.R.color; if (x === -1) stickers.nx = FACE_INFO.L.color; if (y === -1) stickers.ny = FACE_INFO.U.color; if (y === 1) stickers.py = FACE_INFO.D.color; if (z === 1) stickers.pz = FACE_INFO.F.color; if (z === -1) stickers.nz = FACE_INFO.B.color; pieces.push({ id: `${x}${y}${z}`, pos:[x,y,z], stickers }); } return pieces; }
function rotateVector([x,y,z], axis, dir) { if (axis === 0) return [x, dir === 1 ? -z : z, dir === 1 ? y : -y]; if (axis === 1) return [dir === 1 ? z : -z, y, dir === 1 ? -x : x]; return [dir === 1 ? -y : y, dir === 1 ? x : -x, z]; }
function applyMove(cube, face, prime = false) { const { axis, sign } = FACE_INFO[face]; const dir = (prime ? sign : -sign); return cube.map((piece) => { if (piece.pos[axis] !== sign) return piece; const pos = rotateVector(piece.pos, axis, dir); const stickers = {}; for (const [side, color] of Object.entries(piece.stickers)) { const vector = rotateVector(DIR_VECTOR[side], axis, dir); const newSide = Object.keys(DIR_VECTOR).find((key) => DIR_VECTOR[key].every((n, i) => n === vector[i])); stickers[newSide] = color; } return { ...piece, pos, stickers }; }); }
function isCubeSolved(cube) { const faces = { R: ['px', 0, 1], L: ['nx', 0, -1], U: ['ny', 1, -1], D: ['py', 1, 1], F: ['pz', 2, 1], B: ['nz', 2, -1] }; return Object.entries(faces).every(([face, [side, axis, sign]]) => cube.filter((piece) => piece.pos[axis] === sign).length === 9 && cube.filter((piece) => piece.pos[axis] === sign).every((piece) => piece.stickers[side] === FACE_INFO[face].color)); }
function RubiksCube() {
  const [cube, setCube] = useState(makeCube); const [view, setView] = useState({ x: -24, y: -34 }); const [moves, setMoves] = useState(0); const [history, setHistory] = useState([]); const [drag, setDrag] = useState(null); const [message, setMessage] = useState('Solved cube · make a face turn to begin'); const [best, setBest] = useState(() => { try { return Number(localStorage.getItem('arcade:cube-best')) || 0; } catch { return 0; } });
  const faceTurn = (face, prime = false, save = true) => { if (save) setHistory((v) => [...v.slice(-80), cube]); const next = applyMove(cube, face, prime); setCube(next); setMoves((v) => v + 1); if (isCubeSolved(next) && moves > 0) { setMessage(`Solved in ${moves + 1} turns!`); setBest((old) => { const bestValue = old ? Math.min(old, moves + 1) : moves + 1; try { localStorage.setItem('arcade:cube-best', String(bestValue)); } catch {} return bestValue; }); } else setMessage(`${FACE_INFO[face].label} face ${prime ? 'counterclockwise' : 'clockwise'}`); };
  const scramble = () => { const names = Object.keys(FACE_INFO); const count = 20; let next = cube; for (let i = 0; i < count; i += 1) next = applyMove(next, names[Math.floor(Math.random() * names.length)], Math.random() < .5); setCube(next); setHistory([]); setMoves(0); setMessage('Scrambled · solve the cube or reset it'); };
  const reset = () => { setCube(makeCube()); setHistory([]); setMoves(0); setMessage('Cube solved · all faces are reset'); };
  const undo = () => { if (!history.length) return; setCube(history.at(-1)); setHistory((v) => v.slice(0, -1)); setMoves((v) => Math.max(0, v - 1)); setMessage('Last face turn undone'); };
  const moveButtons = [['U','Up'],['R','Right'],['F','Front'],['D','Down'],['L','Left'],['B','Back']];
  useEffect(() => { const onKey = (event) => { if (!/^[urfdlb]$/i.test(event.key) || event.target.matches('input, textarea, select, button')) return; event.preventDefault(); faceTurn(event.key.toUpperCase(), event.shiftKey); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); });
  return <div className="physics-game"><div className="arcade-game-top"><div className="arcade-stats"><Stat label="Turns" value={moves} accent /><Stat label="Best solve" value={best || '—'} /><Stat label="State" value={moves ? 'In progress' : 'Ready'} /></div><div className="arcade-actions"><GameAction onClick={undo} disabled={!history.length}><RotateCcw size={15} /> Undo</GameAction><GameAction onClick={scramble}><Shuffle size={15} /> Scramble</GameAction><GameAction variant="primary" onClick={reset}>Reset cube</GameAction></div></div>
    <p className="physics-hint"><Sparkles size={15} /> {message} · Drag to rotate the view. Turn faces with the controls or keyboard.</p>
    <div className="rubiks-stage" onPointerDown={(e) => { if (e.target.closest('button')) return; e.currentTarget.setPointerCapture(e.pointerId); setDrag([e.clientX, e.clientY]); }} onPointerMove={(e) => { if (!drag) return; const dx = e.clientX - drag[0]; const dy = e.clientY - drag[1]; setView((v) => ({ x: v.x - dy * .45, y: v.y + dx * .55 })); setDrag([e.clientX, e.clientY]); }} onPointerUp={() => setDrag(null)} onPointerCancel={() => setDrag(null)}><div className="rubiks-cube" style={{ transform:`rotateX(${view.x}deg) rotateY(${view.y}deg)` }}>{cube.map((piece) => <div className="rubiks-piece" key={piece.id} style={{ transform:`translate3d(${piece.pos[0] * 36}px,${piece.pos[1] * 36}px,${piece.pos[2] * 36}px)` }}>{DIRS.map((dir) => <span key={dir} className={`rubiks-sticker rubiks-${dir}`} style={{ '--sticker': piece.stickers[dir] || '#111827' }} />)}</div>)}</div><span className="cube-drag-label">Drag to orbit</span></div>
    <div className="cube-turn-grid">{moveButtons.map(([face,label]) => <div className="cube-turn-group" key={face}><strong>{label}</strong><button onClick={() => faceTurn(face)} aria-label={`${label} face clockwise`}>{face}</button><button onClick={() => faceTurn(face, true)} aria-label={`${label} face counterclockwise`}>{face}<sup>′</sup></button></div>)}</div><div className="physics-footer"><span>Keyboard: U · R · F · D · L · B (hold Shift to reverse)</span><div className="cube-mobile-buttons">{moveButtons.slice(0,3).map(([face]) => <button key={face} onClick={() => faceTurn(face)}>{face}</button>)}</div></div>
  </div>;
}

function Pong() {
  const [player, setPlayer] = useState(.5); const [bot, setBot] = useState(.5); const playerRef = useRef(.5); const botRef = useRef(.5); const [ball, setBall] = useState({ x: .5, y: .5 }); const ballRef = useRef({ x: .5, y: .5 }); const velocity = useRef({ x: .48, y: .2 }); const [scores, setScores] = useState({ you: 0, bot: 0 }); const scoresRef = useRef({ you: 0, bot: 0 }); const [difficulty, setDifficulty] = useState('Normal'); const [status, setStatus] = useState('ready'); const [best, setBest] = useState(() => { try { return Number(localStorage.getItem('arcade:pong-best')) || 0; } catch { return 0; } }); const arena = useRef(null); const frame = useRef(0); const last = useRef(0);
  const setPaddle = (value) => { const next = Math.max(.1, Math.min(.9, value)); playerRef.current = next; setPlayer(next); };
  const reset = (start = false) => { const fresh = { you: 0, bot: 0 }; scoresRef.current = fresh; setScores(fresh); const ballStart = { x: .5, y: .5 }; ballRef.current = ballStart; setBall(ballStart); playerRef.current = .5; setPlayer(.5); botRef.current = .5; setBot(.5); velocity.current = { x: Math.random() > .5 ? .48 : -.48, y: (Math.random() - .5) * .58 }; setStatus(start ? 'playing' : 'ready'); last.current = 0; };
  useEffect(() => { const key = (e) => { if (e.key === 'ArrowUp' || e.key.toLowerCase() === 'w') { e.preventDefault(); setPaddle(playerRef.current - .065); } if (e.key === 'ArrowDown' || e.key.toLowerCase() === 's') { e.preventDefault(); setPaddle(playerRef.current + .065); } if (e.code === 'Space') { e.preventDefault(); setStatus((v) => v === 'playing' ? 'paused' : v === 'paused' ? 'playing' : v); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, []);
  useEffect(() => { if (status !== 'playing') return undefined; const tick = (now) => { const dt = Math.min(.04, (now - (last.current || now)) / 1000); last.current = now; const current = { ...ballRef.current }; const vel = velocity.current; current.x += vel.x * dt; current.y += vel.y * dt; const botSpeed = difficulty === 'Easy' ? .44 : difficulty === 'Normal' ? .72 : 1.15; const target = vel.x > 0 ? current.y : .5; botRef.current += Math.sign(target - botRef.current) * Math.min(Math.abs(target - botRef.current), botSpeed * dt); setBot(botRef.current);
      if (current.y < .035 || current.y > .965) { vel.y *= -1; current.y = Math.max(.035, Math.min(.965, current.y)); }
      if (vel.x < 0 && current.x < .075 && Math.abs(current.y - playerRef.current) < .13) { current.x = .075; vel.x = Math.abs(vel.x) * 1.045; vel.y += (current.y - playerRef.current) * .7; }
      else if (vel.x < 0 && current.x < .04) { const s = { ...scoresRef.current, bot: scoresRef.current.bot + 1 }; scoresRef.current = s; setScores(s); current.x = .5; current.y = .5; vel.x = .48; vel.y = (Math.random() - .5) * .55; if (s.bot >= 7) setStatus('done'); }
      if (vel.x > 0 && current.x > .925 && Math.abs(current.y - botRef.current) < .13) { current.x = .925; vel.x = -Math.abs(vel.x) * 1.045; vel.y += (current.y - botRef.current) * .55; }
      else if (vel.x > 0 && current.x > .96) { const s = { ...scoresRef.current, you: scoresRef.current.you + 1 }; scoresRef.current = s; setScores(s); current.x = .5; current.y = .5; vel.x = -.48; vel.y = (Math.random() - .5) * .55; if (s.you >= 7) { setStatus('done'); setBest((v) => { const next = v + 1; try { localStorage.setItem('arcade:pong-best', String(next)); } catch {} return next; }); } }
      ballRef.current = current; setBall(current); if (status === 'playing') frame.current = requestAnimationFrame(tick);
    }; frame.current = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame.current); }, [best, difficulty, status]);
  const pointerMove = (event) => { if (!arena.current) return; const rect = arena.current.getBoundingClientRect(); setPaddle((event.clientY - rect.top) / rect.height); };
  const winner = scores.you >= 7 ? 'You win!' : 'The bot wins';
  return <div className="physics-game"><div className="arcade-game-top"><div className="arcade-stats"><Stat label="You" value={scores.you} accent /><Stat label="Arcade bot" value={scores.bot} /><Stat label="First to" value="7" /></div><div className="arcade-actions"><label className="compact-select">Difficulty<select value={difficulty} onChange={(e) => setDifficulty(e.target.value)}><option>Easy</option><option>Normal</option><option>Expert</option></select></label><GameAction onClick={() => reset(true)}><RotateCcw size={15} /> New match</GameAction></div></div>
    <div className="pong-arena" ref={arena} onPointerMove={pointerMove} onPointerDown={pointerMove}><div className="pong-divider" /><div className="pong-paddle pong-left" style={{ top:`${player * 100}%` }} /><div className="pong-paddle pong-right" style={{ top:`${bot * 100}%` }} /><div className="pong-ball" style={{ left:`${ball.x * 100}%`, top:`${ball.y * 100}%` }} /><div className="pong-score pong-score--you">{scores.you}</div><div className="pong-score pong-score--bot">{scores.bot}</div>{status !== 'playing' && <div className="pong-overlay"><strong>{status === 'ready' ? 'Neon Pong' : status === 'paused' ? 'Match paused' : winner}</strong><span>{status === 'ready' ? 'Move your paddle and be the first to score seven.' : status === 'paused' ? 'Press resume when you’re ready.' : `${scores.you} : ${scores.bot}`}</span><GameAction variant="primary" onClick={() => status === 'paused' ? setStatus('playing') : reset(true)}>{status === 'done' ? 'Play rematch' : status === 'paused' ? 'Resume match' : 'Start match'}</GameAction></div>}</div>
    <div className="physics-footer"><span>Move with mouse, touch, ↑ / ↓ or W / S · Space pauses</span><span className="pong-best"><Trophy size={14} /> Career wins: {best}</span></div><div className="pong-touch-controls"><button onClick={() => setPaddle(playerRef.current - .11)} aria-label="Move paddle up"><ArrowUp size={18} /></button><button onClick={() => setPaddle(playerRef.current + .11)} aria-label="Move paddle down"><ArrowDown size={18} /></button></div>
  </div>;
}

export { Pong, RubiksCube };
