export const toolRegistry = [
  {
    id: 'word-counter',
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, paragraphs, and reading time as you write.',
    categorySlug: 'text',
    icon: 'FileText',
    tags: ['writing', 'words', 'sentences', 'reading time'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'character-counter',
    slug: 'character-counter',
    name: 'Character Counter',
    description: 'Track characters, spaces, words, and lines with an optional live character limit.',
    categorySlug: 'text',
    icon: 'Type',
    tags: ['characters', 'social media', 'limit', 'spaces'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'case-converter',
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Change text to uppercase, lowercase, title case, sentence case, and more.',
    categorySlug: 'text',
    icon: 'CaseSensitive',
    tags: ['uppercase', 'lowercase', 'title case', 'formatting'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
];
