export const toolRegistry = [
  {
    id: 'word-counter',
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, paragraphs, and reading time as you write.',
    categorySlug: 'text',
    icon: 'FileText',
    tags: ['writing', 'words', 'sentences', 'reading time'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'character-counter',
    slug: 'character-counter',
    name: 'Character Counter',
    description: 'Track characters, spaces, words, and lines with an optional live character limit.',
    categorySlug: 'text',
    icon: 'Type',
    tags: ['characters', 'social media', 'limit', 'spaces'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'case-converter',
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Change text to uppercase, lowercase, title case, sentence case, and more.',
    categorySlug: 'text',
    icon: 'CaseSensitive',
    tags: ['uppercase', 'lowercase', 'title case', 'formatting'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, minify, and validate JSON in your browser with readable error feedback.',
    categorySlug: 'developer',
    icon: 'Braces',
    tags: ['json', 'format', 'minify', 'validate', 'developer'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'url-encoder-decoder',
    slug: 'url-encoder-decoder',
    name: 'URL Encoder & Decoder',
    description: 'Encode or decode URL components and full URLs without leaving your device.',
    categorySlug: 'developer',
    icon: 'Link2',
    tags: ['url', 'encode', 'decode', 'percent encoding', 'developer'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'base64-encoder-decoder',
    slug: 'base64-encoder-decoder',
    name: 'Base64 Encoder & Decoder',
    description: 'Convert text to Base64 or decode Base64 back to UTF-8 text, including Unicode.',
    categorySlug: 'developer',
    icon: 'Binary',
    tags: ['base64', 'encode', 'decode', 'unicode', 'developer'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'password-generator',
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong random passwords in your browser with controls for length and character types.',
    categorySlug: 'developer',
    icon: 'KeyRound',
    tags: ['password', 'security', 'random', 'generator'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Create random UUID v4 identifiers locally for development and testing.',
    categorySlug: 'developer',
    icon: 'Fingerprint',
    tags: ['uuid', 'guid', 'identifier', 'random', 'developer'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'slug-generator',
    slug: 'slug-generator',
    name: 'URL Slug Generator',
    description: 'Turn a title or phrase into a clean, lowercase URL slug.',
    categorySlug: 'text',
    icon: 'Link2',
    tags: ['slug', 'url', 'seo', 'title', 'text'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'timestamp-converter',
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to readable dates and dates back to seconds or milliseconds.',
    categorySlug: 'developer',
    icon: 'Clock3',
    tags: ['timestamp', 'unix', 'epoch', 'date', 'time'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'color-converter',
    slug: 'color-converter',
    name: 'Color Converter',
    description: 'Convert colors between HEX, RGB, and HSL formats with a live preview.',
    categorySlug: 'developer',
    icon: 'Palette',
    tags: ['color', 'hex', 'rgb', 'hsl', 'design'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'gradient-generator',
    slug: 'gradient-generator',
    name: 'CSS Gradient Generator',
    description: 'Build a CSS linear gradient, preview it, and copy the generated code.',
    categorySlug: 'developer',
    icon: 'Blend',
    tags: ['css', 'gradient', 'color', 'design', 'background'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'html-entity-encoder',
    slug: 'html-entity-encoder',
    name: 'HTML Entity Encoder',
    description: 'Encode special characters as HTML entities or decode entities back to readable text.',
    categorySlug: 'developer',
    icon: 'Code2',
    tags: ['html', 'entities', 'escape', 'encode', 'decode', 'developer'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'regex-tester',
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Try a regular expression against sample text and inspect each match and capture group.',
    categorySlug: 'developer',
    icon: 'Braces',
    tags: ['regex', 'regular expression', 'pattern', 'match', 'developer'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'number-base-converter',
    slug: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert whole numbers between decimal, binary, octal, and hexadecimal.',
    categorySlug: 'developer',
    icon: 'Binary',
    tags: ['number', 'base', 'binary', 'decimal', 'hexadecimal', 'octal'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'lorem-ipsum-generator',
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder paragraphs for layouts, prototypes, and design mockups.',
    categorySlug: 'text',
    icon: 'FileText',
    tags: ['lorem ipsum', 'placeholder', 'dummy text', 'paragraphs', 'writing'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'text-diff-checker',
    slug: 'text-diff-checker',
    name: 'Text Diff Checker',
    description: 'Compare two versions of text and see which lines were added, removed, or left unchanged.',
    categorySlug: 'developer',
    icon: 'Braces',
    tags: ['diff', 'compare', 'text', 'changes', 'developer'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'csv-to-json',
    slug: 'csv-to-json',
    name: 'CSV to JSON Converter',
    description: 'Convert comma-separated data into a JSON array using the first row as column names.',
    categorySlug: 'developer',
    icon: 'Braces',
    tags: ['csv', 'json', 'convert', 'data', 'developer'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'markdown-table-generator',
    slug: 'markdown-table-generator',
    name: 'Markdown Table Generator',
    description: 'Turn tab-separated rows into a Markdown table that is ready to paste into a document or README.',
    categorySlug: 'developer',
    icon: 'FileText',
    tags: ['markdown', 'table', 'tsv', 'format', 'developer'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'percentage-calculator',
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate a percentage of a value and the percentage change between two values.',
    categorySlug: 'calculators',
    icon: 'Type',
    tags: ['percentage', 'percent', 'change', 'calculator', 'math'],
    isPopular: false,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
];
