export const toolRegistry = [
  {
    id: 'word-counter',
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, paragraphs, and reading time as you write.',
    categorySlug: 'text',
    icon: 'FileText',
    tags: ['writing', 'words', 'sentences', 'reading time'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'character-counter',
    slug: 'character-counter',
    name: 'Character Counter',
    description: 'Track characters, spaces, words, and lines with an optional live character limit.',
    categorySlug: 'text',
    icon: 'Type',
    tags: ['characters', 'social media', 'limit', 'spaces'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'case-converter',
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Change text to uppercase, lowercase, title case, sentence case, and more.',
    categorySlug: 'text',
    icon: 'CaseSensitive',
    tags: ['uppercase', 'lowercase', 'title case', 'formatting'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, minify, and validate JSON in your browser with readable error feedback.',
    categorySlug: 'developer',
    icon: 'Braces',
    tags: ['json', 'format', 'minify', 'validate', 'developer'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'url-encoder-decoder',
    slug: 'url-encoder-decoder',
    name: 'URL Encoder & Decoder',
    description: 'Encode or decode URL components and full URLs without leaving your device.',
    categorySlug: 'developer',
    icon: 'Link2',
    tags: ['url', 'encode', 'decode', 'percent encoding', 'developer'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
  {
    id: 'base64-encoder-decoder',
    slug: 'base64-encoder-decoder',
    name: 'Base64 Encoder & Decoder',
    description: 'Convert text to Base64 or decode Base64 back to UTF-8 text, including Unicode.',
    categorySlug: 'developer',
    icon: 'Binary',
    tags: ['base64', 'encode', 'decode', 'unicode', 'developer'],
    isPopular: true,
    isFeatured: true,
    isNew: true,
    processingType: 'client',
  },
];
